import { Unit } from "@/types/realestate";

export const mockUnits: Unit[] = [
  {
    id: "1",
    title: "فيلا فاخرة في كمباوند بالم هيلز",
    type: "فيلا",
    for: "بيع",
    country: "مصر",
    city: "الشيخ زايد",
    developerId: "dev1",
    compoundId: "comp1",
    price: 12000000,
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    images: ["/file.svg"],
    rating: 4.8,
    description: "فيلا بتشطيب سوبر لوكس وحديقة خاصة وحمام سباحة.",
    features: ["حديقة", "حمام سباحة", "تشطيب فاخر"],
    ownerName: "Palm Hills",
    garden: true,
    pool: true,
    floors: 2,
  },
  {
    id: "2",
    title: "شقة فاخرة في التجمع الخامس",
    type: "شقة",
    for: "ايجار",
    country: "مصر",
    city: "القاهرة الجديدة",
    developerId: "dev2",
    compoundId: "comp2",
    price: 25000,
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    images: ["/window.svg"],
    rating: 4.5,
    description: "شقة مفروشة بالكامل في موقع مميز.",
    features: ["مفروشة", "موقع مركزي"],
    ownerName: "Mountain View",
    garden: false,
    pool: false,
    floors: 1,
  },
  {
    id: "3",
    title: "قصر فاخر في الساحل الشمالي",
    type: "قصر",
    for: "بيع",
    country: "مصر",
    city: "الساحل الشمالي",
    developerId: "dev3",
    compoundId: "comp3",
    price: 45000000,
    bedrooms: 8,
    bathrooms: 7,
    area: 1200,
    images: ["/globe.svg"],
    rating: 5,
    description: "قصر على البحر مباشرة مع مسبح وحديقة ضخمة.",
    features: ["مسبح خاص", "إطلالة بحرية", "حديقة ضخمة"],
    ownerName: "Emaar Misr",
    garden: true,
    pool: true,
    floors: 3,
  },
];
