import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import FilterBar from "@/components/FilterBar";
import { mockUnits } from "@/types/mockUnits";
import AdsBar from "@/components/AdsBar";
import VoiceSearch from "@/components/VoiceSearch";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import ChatBot from "@/components/ChatBot";
import { useState } from "react";
import UnitCard from "@/components/UnitCard";
import RealestateLiveLogo from "@/components/RealestateLiveLogo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const MapComponent = dynamic(() => import("@/components/MapComponent"), { ssr: false });

export default function Home() {
  const [filteredUnits, setFilteredUnits] = useState(mockUnits);

  // فلترة الوحدات بناءً على القيم المدخلة
  const handleFilter = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    let units = mockUnits;
    if (data.get("country")) units = units.filter(u => u.country === data.get("country"));
    if (data.get("type")) units = units.filter(u => u.type === data.get("type"));
    if (data.get("for")) units = units.filter(u => u.for === data.get("for"));
    if (data.get("developer")) units = units.filter(u => u.developerId === data.get("developer"));
    if (data.get("compound")) units = units.filter(u => u.compoundId === data.get("compound"));
    if (data.get("minPrice")) units = units.filter(u => u.price >= Number(data.get("minPrice")));
    if (data.get("maxPrice")) units = units.filter(u => u.price <= Number(data.get("maxPrice")));
    if (data.get("bedrooms")) units = units.filter(u => u.bedrooms === Number(data.get("bedrooms")));
    if (data.get("bathrooms")) units = units.filter(u => u.bathrooms === Number(data.get("bathrooms")));
    if (data.get("area")) units = units.filter(u => u.area >= Number(data.get("area")));
    if (data.get("floors")) units = units.filter(u => u.floors === Number(data.get("floors")));
    if (data.get("pool") === "yes") units = units.filter(u => u.pool);
    if (data.get("pool") === "no") units = units.filter(u => !u.pool);
    if (data.get("garden") === "yes") units = units.filter(u => u.garden);
    if (data.get("garden") === "no") units = units.filter(u => !u.garden);
    setFilteredUnits(units);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="animatedBg" />
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <AdsBar />
          <div style={{display:'flex',justifyContent:'center',alignItems:'center',margin:'24px 0 0 0'}}>
        <RealestateLiveLogo size={44} />
      </div>
          <div style={{display:'flex',justifyContent:'center',alignItems:'center',marginTop:8}}>
        <VoiceSearch onResult={(text) => alert(`نتيجة البحث الصوتي: ${text}`)} />
      </div>
          <FilterBar onSubmit={handleFilter} />
          {/* خريطة تفاعلية للوحدات العقارية */}
          <div style={{ width: "100%", maxWidth: 900, margin: "32px auto" }}>
            <MapComponent units={filteredUnits} />
          </div>

          {/* عرض نتائج الوحدات */}
          <div style={{display:'flex',flexWrap:'wrap',justifyContent:'center',margin:'32px auto',maxWidth:1200}}>
          {filteredUnits.length === 0 ? (
            <div style={{color:'#b00',fontWeight:'bold',fontSize:'1.2rem',margin:'32px'}}>لا توجد وحدات مطابقة للبحث</div>
          ) : (
            filteredUnits.map(unit => <UnitCard key={unit.id} unit={unit} />)
          )}
        </div>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
        <ChatBot />
      </div>
    </>
  );
}
